version: '3.8'

services:
  nobel-prize-explorer:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped